FROM golang:1.11.1-alpine 

#ENV GOPATH /usr/src/app

CMD echo $GOPATH

WORKDIR /go/src/topz

RUN apk --no-cache add ca-certificates git

COPY pkg  /go/src/topz/pkg
COPY cmd  /go/src/topz/cmd
RUN ls -larhtR /go/src/topz/
#RUN go get -v ./... && \
#    cd /go/src/topz/cmd/server && \
#    CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o topz .
#
